### ISSUE TITLE
Possible bug: Action not performed if task has dependency component added via run_template()

### ISSUE THREAD

**Issue by ghillb** [stevearc/overseer.nvim#12] opened 2022-08-10 14:58 UTC
Suppose the following setup: two tasks templates (`task1` & `task2`) and two `run_template` functions, where in one `task2` is added as  dependency from `task1` and the second just runs `task1`.

My intuition would be that both `run1` and `run2` will open the task terminal for `task1` in a split, but in actuality only `run2` does. 

Is this a bug or for some reason intended?

```lua
local _, overseer = pcall(require, "overseer")

overseer.register_template({
  name = "task1",
  builder = function(params)
    return {
      cmd = {
        "echo",
        "task1",
      },
    }
  end,
})

overseer.register_template({
  name = "task2",
  builder = function(params)
    return {
      cmd = {
        "echo",
        "task2",
      },
    }
  end,
})

local run1 = function()
  overseer.run_template({ name = "task1", autostart = false }, function(task)
    if task then
      task:add_component({
        "dependencies",
        task_names = {
          "task2",
        },
        sequential = true,
      })
      task:start()
      overseer.run_action(task, "open hsplit")
    end
  end)
end

local run2 = function()
  overseer.run_template({ name = "task1", autostart = false }, function(task)
    if task then
      task:start()
      overseer.run_action(task, "open hsplit")
    end
  end)
end

```

**Comment by stevearc** [comment] 2022-08-10 15:30
Thanks for providing a minimal example! This behavior is expected, though I agree that it's perhaps not intuitive or ideal. In the case of `run2()`, you should see a log line (also in `:messages`) that says `[WARN] Cannot perform action 'open hsplit'`. This is what happens when the action precondition is not met
https://github.com/stevearc/overseer.nvim/blob/c17a27821396d76d1ac5759ccefaa000f10d534d/lua/overseer/task_list/actions.lua#L114-L117

What's happening is when task1 is started, it actually *does not* immediately start running, because it has to kick off its dependencies and wait for them to start. Since it doesn't immediately start running a process, it does not yet have a terminal buffer, and the `open hsplit` action fails because the bufnr is `nil`.

The easiest way around this is to wait until the task *really* starts before opening the split:
```lua
task:subscribe("on_start", function()
  overseer.run_action(task, "open hsplit")
  return false -- this will unsubscribe the callback
end)
```

**Comment by ghillb** [comment] 2022-08-10 15:58
I see, thanks for the explanation! I have another question, why is the output "task1" from the `task1` command (`echo task1`) not appearing in the opened task terminal, when running it?

**Comment by stevearc** [comment] 2022-08-10 16:03
Uh...that is definitely unexpected and I cannot reproduce that behavior. You're saying after running the template with `{cmd = {"echo", "task1"}}`, when you open the terminal via any means there's nothing in the buffer? Does it at least show the `[Process exited 0]` message?

**Comment by ghillb** [comment] 2022-08-10 16:18
Yep, this is how it looks, after running `task1`:
![image](https://user-images.githubusercontent.com/35503959/183960666-bab14972-60ec-462e-9b01-b748690cea18.png)

The terminal opened via action (with `[Process exited 0]` but without output) and the Overseer task list to the right (with output). The terminal is also empty (except `[Process exited 0]`) if I open it via the task list.

**Comment by stevearc** [comment] 2022-08-10 17:44
Interesting. And it's not just that the text has been scrolled off of the window? If you focus the terminal and go to the top, it still doesn't have the text?

I wonder if maybe something is swallowing the first line of output. If you echo two or three lines, do any of them show up?

Last question: what version of Neovim are you using?

**Comment by ghillb** [comment] 2022-08-10 18:50
No, it's not scrolled off the window, the text is not there. Here is a test with 4 lines of output:
![image](https://user-images.githubusercontent.com/35503959/183990910-f93ce7f0-341b-469e-9257-e8d43804a17f.png)
My neovim version is `NVIM v0.8.0-dev`. 
This is just odd, the `cat --help` output does not show up in the task terminal, but for `docker --help` it does.

**Comment by stevearc** [comment] 2022-08-11 05:55
Well I tried on neovim nightly and I still couldn't reproduce it. This is very strange behavior, and quite possibly a bug in neovim. Do you see the same issues if you directly run the echo/cat command with `:call termopen(['cat', '--help'])`? Just trying to narrow it down to a minimal repro

**Comment by ghillb** [comment] 2022-08-11 16:30
You are correct, the output of `:call termopen(['cat', '--help'])` is also empty, and it is not an issue with Overseer.

The culprit was the following auto command:
```lua
vim.api.nvim_create_autocmd(
  { "TermEnter", "TermOpen" },
  {
    command = "set ft=terminal",
    group = vim.api.nvim_create_augroup("TermGroup", { clear = true })
  }
) 
```
After changing it to the below one, everything works.
```lua
vim.api.nvim_create_autocmd(
  { "TermEnter", "TermOpen" },
  {
    command = "call timer_start(50, { tid -> execute('set ft=terminal')})",
    group = vim.api.nvim_create_augroup("TermGroup", { clear = true }),
  }
)
```
Setting the filetype of a terminal buffer, immediately after creating it, seems to be the cause.

**Comment by stevearc** [comment] 2022-08-11 16:58
Whoah, that's still pretty surprising. Do you have any behavior in a `ftplugin/terminal.lua` file that could explain the buffer clearing?

Also, some general info that may help:
- Terminals set `buftype = terminal`. In many cases, you can use that instead of setting the filetype.
- The `TermOpen` event is dangerous, because the `termopen()` function will cause it to be triggered _even though_ the current buffer is _not_ a terminal. I recommend that any actions you take in this autocmd you first check `if vim.api.nvim_buf_get_option(0, 'buftype') == 'terminal'`

**Comment by stevearc** [comment] 2022-08-11 17:57
Very strange, but glad you got it working. Closing this out as it sounds like the original issue is resolved

**Closed by stevearc** 2022-08-11 17:57 UTC
